export const CLEAR_MESSAGE = 'CLEAR_MESSAGE';
export const USERNAME = 'USERNAME';
export const PASSWORD = 'PASSWORD';
export const TOKEN = 'TOKEN';
export const GITHUB_ACCOUNT = 'GITHUB_ACCOUNT';
export const FETCH_USER_REPOS = 'FETCH_USER_REPOS';
export const FETCH_USER_REPOS_FAILURE = 'FETCH_USER_REPOS_FAILURE';
export const FETCH_USER_REPOS_SUCCESS = 'FETCH_USER_REPOS_SUCCESS';
export const FETCH_ACCOUNT = 'FETCH_ACCOUNT';
export const FETCH_ACCOUNT_SUCCESS = 'FETCH_ACCOUNT_SUCCESS';
export const FETCH_ACCOUNT_FAILURE = 'FETCH_ACCOUNT_FAILURE';
export const FETCH_GET_TOKEN = 'FETCH_GET_TOKEN';
export const FETCH_GET_TOKEN_SUCCESS = 'FETCH_GET_TOKEN_SUCCESS';
export const FETCH_GET_TOKEN_FAILURE = 'FETCH_GET_TOKEN_FAILURE';

export const FETCH_STARRED_REPO = 'FETCH_STARRED_REPO';
export const FETCH_STARRED_REPO_SUCCESS = 'FETCH_STARRED_REPO_SUCCESS';
export const FETCH_STARRED_REPO_FAILURE = 'FETCH_STARRED_REPO_FAILURE';

export const REPOS = 'REPOS';
export const SET_PAGE = 'SET_PAGE';

export const WATCH_REPO = 'WATCH_REPO';
export const WATCH_REPO_SUCCESS = 'WATCH_REPO_SUCCESS';
export const WATCH_REPO_FAILURE = 'WATCH_REPO_FAILURE';

export const STAR_REPO = 'STAR_REPO';
export const STAR_REPO_SUCCESS = 'STAR_REPO_SUCCESS';
export const STAR_REPO_FAILURE = 'STAR_REPO_FAILURE';

export const FORK_REPO = 'FORK_REPO';
export const FORK_REPO_SUCCESS = 'FORK_REPO_SUCCESS';
export const FORK_REPO_FAILURE = 'FORK_REPO_FAILURE';

export const FETCH_REPO_ISSUES = 'FETCH_REPO_ISSUES';
export const FETCH_REPO_ISSUES_SUCCESS = 'FETCH_REPO_ISSUES_SUCCESS';
export const FETCH_REPO_ISSUES_FAILURE = 'FETCH_REPO_ISSUES_FAILURE';

export const FETCH_REPO_PULL = 'FETCH_REPO_PULL';
export const FETCH_REPO_PULL_SUCCESS = 'FETCH_REPO_PULL_SUCCESS';
export const FETCH_REPO_PULL_FAILURE = 'FETCH_REPO_PULL_FAILURE';

export const OPEN_PROJECT_DETAILS = 'OPEN_PROJECT_DETAILS';

export const FETCH_UPDATE_REPO = 'FETCH_WATCHS_REPO';
export const FETCH_UPDATE_REPO_SUCCESS = 'FETCH_UPDATE_REPO_SUCESS';
export const FETCH_UPDATE_REPO_FAILURE = 'FETCH_UPDATE_REPO_FAILURE';
